### ISSUE TITLE
Ignoring building Boost.Locale for iOS

### ISSUE THREAD

**Issue by alexandrkirilov** [faithfracture/Apple-Boost-BuildScript#61] opened 2020-11-25 15:43 UTC
This script is ignoring building Boost.Locale. 
I know how to build Boost.Locale for MacOS. 
I've tried to add ICU support but it's not working with your script.

**Comment by alexandrkirilov** [comment] 2020-11-25 15:44
`Decomposing libboost_locale.a
Unpacking /Users/alexandr/Projects/boost_apple/Apple-Boost-BuildScript/build/boost/1.73.0/ios/release/build/arm64/obj/locale
ar: ../../libboost_locale.a: No such file or directory
mv: rename *.o to locale_*.o: No such file or directory
Unpacking /Users/alexandr/Projects/boost_apple/Apple-Boost-BuildScript/build/boost/1.73.0/ios/release/build/x86_64/obj/locale
Linking each architecture into an uberlib ( libboost_atomic.a libboost_chrono.a libboost_date_time.a libboost_exception.a libboost_filesystem.a libboost_program_options.a libboost_random.a libboost_system.a libboost_thread.a libboost_unit_test_framework.a libboost_locale.a => libboost.a )
rm: /Users/alexandr/Projects/boost_apple/Apple-Boost-BuildScript/build/boost/1.73.0/ios/release/build/arm64/libboost.a: No such file or directory
Archiving atomic
`

**Comment by faithfracture** [comment] 2020-11-26 14:55
Duplicate of #41

**Closed by faithfracture** 2020-11-26 14:55 UTC
